# Generated by Django 5.2.6 on 2025-09-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_client_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='subcription_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
