# Generated by Django 5.2.6 on 2025-09-25 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_client_subcription_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='subcription_type',
            new_name='subscription_type',
        ),
    ]
