# Generated by Django 5.2.6 on 2025-09-25 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_ticketsactivityticket_related_tickets_id_and_more'),
        ('users', '0009_alter_client_address_alter_client_subscription_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketsCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticketscustomer')),
            ],
            options={
                'db_table': 'tickets_customer_count',
            },
        ),
    ]
