# Generated by Django 5.2.6 on 2025-09-25 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_ticketscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketscount',
            name='ticket_customer',
        ),
        migrations.AddField(
            model_name='ticketscount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ticketscount'),
        ),
    ]
