# Generated by Django 5.2.6 on 2025-09-25 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticketscustomer_user'),
        ('users', '0011_remove_ticketscount_ticket_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketscount',
            name='ticket_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.ticketscustomer'),
        ),
    ]
