# Generated by Django 5.2.6 on 2025-09-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_ticketscount_ticket_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tickets_this_month',
            field=models.BigIntegerField(blank=True, max_length=20, null=True),
        ),
    ]
