# Generated by Django 5.2.6 on 2025-09-26 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_client_tickets_this_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketscount',
            name='ticket_customer',
        ),
    ]
