# Generated by Django 5.2.6 on 2025-09-26 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_alter_ticketscustomer_tickets_of_year_ticketssummary'),
        ('users', '0014_remove_ticketscount_ticket_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTicketSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_count', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticketscustomer')),
            ],
        ),
        migrations.DeleteModel(
            name='TicketsCount',
        ),
    ]
