# Generated by Django 5.2.6 on 2025-09-26 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_customerticketsummary_delete_ticketscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tickets_this_month',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerticketsummary',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.client'),
        ),
    ]
