# Generated by Django 5.2.6 on 2025-09-26 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_client_tickets_this_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerticketsummary',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_summaries', to='users.client'),
        ),
    ]
