# Generated by Django 5.2.6 on 2025-09-26 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_customerticketsummary_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='tickets_this_month',
        ),
    ]
