# Generated by Django 5.2.6 on 2025-09-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_client_tickets_this_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='client',
            name='subscription_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('6_month', '6 Month'), ('Annualy', 'Annualy'), ('other', 'Other')], default='monthly', max_length=20),
        ),
    ]
