# Generated by Django 5.2.6 on 2025-09-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_client_ceo_birthday_client_ceo_email_client_ceo_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(default='-'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ceo_email',
            field=models.EmailField(default='-', max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='ceo_name',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='ceo_phone',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='vat_nif',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
