# Generated by Django 5.2.6 on 2025-09-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_client_address_alter_client_ceo_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ceo_birthday',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
