# Generated by Django 5.2.6 on 2025-09-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_client_ceo_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='subscription_other',
            field=models.CharField(blank=True, help_text="Specify if 'Other' is selected", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
