# Generated by Django 5.2.6 on 2025-09-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_client_subscription_other_alter_client_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='subscription_other',
        ),
    ]
