# Generated by Django 5.2.6 on 2025-09-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_client_subscription_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='States_editing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='subscription_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ceo_birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='subscription_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('6_month', '6 Month'), ('annually', 'Annually'), ('other', 'Other')], default='monthly', max_length=20),
        ),
    ]
