# Generated by Django 5.2.6 on 2025-09-30 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_states_editing_client_subscription_other_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='states_editing',
            options={'verbose_name': 'State_editing', 'verbose_name_plural': 'States_editing'},
        ),
        migrations.RenameField(
            model_name='states_editing',
            old_name='name',
            new_name='state',
        ),
    ]
