# Generated by Django 5.2.6 on 2025-09-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_states_editing_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': '"Client"', 'verbose_name_plural': 'Clients-editing'},
        ),
        migrations.AlterModelOptions(
            name='states_editing',
            options={'verbose_name': '"State"', 'verbose_name_plural': 'States-editing'},
        ),
        migrations.AddField(
            model_name='states_editing',
            name='state_type',
            field=models.CharField(choices=[('current_state', 'Current_state'), ('current_state2', 'Current_state2'), ('next_state', 'Next_state'), ('other', 'Other')], default='', max_length=100),
        ),
    ]
