# Generated by Django 5.2.6 on 2025-09-30 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_remove_ticketscustomer_tickets_of_year_and_more'),
        ('users', '0027_alter_client_options_alter_states_editing_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='states_editing',
            name='activity_ticket',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_editing', to='tickets.ticketsactivityticket'),
        ),
    ]
