# Generated by Django 5.2.6 on 2025-09-30 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_remove_ticketscustomer_tickets_of_year_and_more'),
        ('users', '0028_states_editing_activity_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states_editing',
            name='activity_ticket',
            field=models.ForeignKey(blank=True, default=None, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_editing', to='tickets.ticketsactivityticket'),
        ),
        migrations.AlterField(
            model_name='states_editing',
            name='state_type',
            field=models.CharField(choices=[('current_state', 'Current_state'), ('current_state2', 'Current_state2'), ('next_state', 'Next_state')], default='', max_length=100),
        ),
    ]
