# Generated by Django 5.2.6 on 2025-09-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_states_editing_activity_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states_editing',
            name='state',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
