# Generated by Django 5.2.6 on 2025-09-20 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketsActivityimportance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketsActivitytype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tickets_activitytype',
            },
        ),
        migrations.CreateModel(
            name='TicketsActivitytype2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tickets_activitytype2',
            },
        ),
        migrations.CreateModel(
            name='TicketsAnalystconsultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tickets_analystconsultant',
            },
        ),
        migrations.CreateModel(
            name='TicketsCurrentstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tickets_currentstate',
            },
        ),
        migrations.CreateModel(
            name='TicketsCurrentstate2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tickets_currentstate2',
            },
        ),
        migrations.CreateModel(
            name='TicketsCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'tickets_customer',
            },
        ),
        migrations.CreateModel(
            name='TicketsFinishstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tickets_finishstate',
            },
        ),
        migrations.CreateModel(
            name='TicketsNextstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tickets_nextstate',
            },
        ),
        migrations.CreateModel(
            name='TicketsPendingstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tickets_pendingstate',
            },
        ),
        migrations.CreateModel(
            name='TicketsReportedby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tickets_reportedby',
            },
        ),
        migrations.CreateModel(
            name='TicketsSpecialstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tickets_specialstate',
            },
        ),
        migrations.CreateModel(
            name='TicketsActivityticket',
            fields=[
                ('ticket_id', models.AutoField(db_column='ticket_ID', primary_key=True, serialize=False)),
                ('sysdate', models.DateTimeField()),
                ('reported_user', models.CharField(max_length=100)),
                ('activity_importance', models.CharField(max_length=100)),
                ('activity_title', models.CharField(max_length=100)),
                ('activity_start', models.DateTimeField(blank=True, null=True)),
                ('activity_end', models.DateTimeField(blank=True, null=True)),
                ('activity_resolution_description', models.TextField()),
                ('billing', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('related_tickets_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticketsactivityticket')),
                ('activity_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticketsactivitytype')),
                ('activity_type_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticketsactivitytype2')),
                ('analyst_consultant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticketsanalystconsultant')),
                ('current_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_state', to='tickets.ticketscurrentstate')),
                ('current_state2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_state2', to='tickets.ticketscurrentstate2')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticketscustomer')),
                ('finish_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticketsfinishstate')),
                ('next_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticketsnextstate')),
                ('pending_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticketspendingstate')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticketsreportedby')),
                ('special_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticketsspecialstate')),
            ],
            options={
                'db_table': 'tickets_activityticket',
            },
        ),
    ]
