# Generated by Django 5.2.6 on 2025-09-23 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketsactivityticket_time_spent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsactivityticket',
            name='finish_state',
        ),
        migrations.RemoveField(
            model_name='ticketsactivityticket',
            name='next_state',
        ),
        migrations.RemoveField(
            model_name='ticketsactivityticket',
            name='pending_state',
        ),
        migrations.RemoveField(
            model_name='ticketsactivityticket',
            name='special_state',
        ),
    ]
