# Generated by Django 5.2.6 on 2025-09-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_ticketsactivityticket_finish_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsactivityticket',
            name='time_spent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
