# Generated by Django 5.2.6 on 2025-09-24 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticketsactivityticket_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsactivityticket',
            name='next_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticketsnextstate'),
        ),
    ]
