# Generated by Django 5.2.6 on 2025-09-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticketsactivityticket_next_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsactivityticket',
            name='related_tickets_id',
        ),
        migrations.AddField(
            model_name='ticketsactivityticket',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketsactivityticket',
            name='related_ticket_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
