# Generated by Django 5.2.6 on 2025-09-25 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_ticketsactivityticket_related_tickets_id_and_more'),
        ('users', '0010_ticketscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketscustomer',
            name='user',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to='users.ticketscount'),
            preserve_default=False,
        ),
    ]
