# Generated by Django 5.2.6 on 2025-09-25 13:46

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticketscustomer_user'),  # substituir pelo último número correto
    ]

    operations = [
        migrations.AddField(
            model_name='ticketscustomer',
            name='user',
            field=models.ForeignKey(
                to='users.ticketscount',
                on_delete=models.CASCADE,
                null=True,
                blank=True,
            ),
        ),
    ]