# Generated by Django 5.2.6 on 2025-09-25 13:59

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticketscustomer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketscustomer',
            name='user',
            field=models.ForeignKey(
                to='users.TicketsCount',
                on_delete=django.db.models.deletion.CASCADE,
                null=True,
                blank=True,
            ),
        ),
    ]