# Generated by Django 5.2.6 on 2025-09-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20250925_1446'),
        ('tickets', '0009_auto_20250925_1459'),
    ]

    operations = [
    ]
