# Generated by Django 5.2.6 on 2025-09-25 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_merge_0008_auto_20250925_1446_0009_auto_20250925_1459'),
        ('users', '0013_client_tickets_this_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketscustomer',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='users.ticketscount',
                null=True,
                blank=True
                ),
        ),
    ]
