# Generated by Django 5.2.6 on 2025-09-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_ticketscustomer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsactivityticket',
            name='related_ticket_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
