# Generated by Django 5.2.6 on 2025-09-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_ticketsactivityticket_related_ticket_id'),
    ]

    operations = [
    ]
