# Generated by Django 5.2.6 on 2025-09-25 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20250925_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsactivityticket',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ticketsactivityticket',
            name='related_ticket_id',
        ),
    ]
