# Generated by Django 5.2.6 on 2025-09-25 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_remove_ticketsactivityticket_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsactivityticket',
            name='related_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_tickets', to='tickets.ticketsactivityticket'),
        ),
    ]
