# Generated by Django 5.2.6 on 2025-09-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_ticketsactivityticket_related_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketscustomer',
            name='user',
        ),
        migrations.AddField(
            model_name='ticketscustomer',
            name='tickets_of_year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
