# Generated by Django 5.2.6 on 2025-09-26 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_remove_ticketscustomer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketscustomer',
            name='tickets_of_year',
            field=models.PositiveIntegerField(default=0, max_length=10),
        ),
        migrations.CreateModel(
            name='TicketsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticketscustomer')),
            ],
        ),
    ]
