# Generated by Django 5.2.6 on 2025-09-29 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_alter_ticketscustomer_tickets_of_year_ticketssummary'),
        ('users', '0018_remove_client_tickets_this_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketscustomer',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_customers', to='users.client'),
        ),
    ]
