# Generated by Django 5.2.6 on 2025-09-29 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_alter_ticketsactivityticket_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsactivityticket',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.ticketscustomer'),
        ),
    ]
