# Generated by Django 5.2.6 on 2025-09-29 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_alter_ticketsactivityticket_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketscustomer',
            name='tickets_of_year',
        ),
        migrations.AlterField(
            model_name='ticketsactivityticket',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activitytickets', to='tickets.ticketscustomer'),
        ),
        migrations.AlterModelTable(
            name='ticketscustomer',
            table=None,
        ),
    ]
