# Generated by Django 5.2.6 on 2025-10-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_remove_ticketscustomer_tickets_of_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsactivityticket',
            name='first_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
